---
title: "Simulation study"
author: "August Arnstad"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(formatR)
showsol <- FALSE
library(knitr)
library(devtools)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 68), 
                      tidy = TRUE, 
                      warning = FALSE, 
                      error = FALSE, 
                      message = FALSE, 
                      echo = TRUE, 
                      fig.width=7, 
                      fig.height=5, 
                      fig.align="center")

library(remotes)
library(devtools)
if(!require(devtools)) install.packages("devtools")
devtools::install_github("AugustArnstad/VariableImportanceINLA")
library(VariableImportanceINLA)
library(INLA)
library(MASS)
library(dplyr)
```


```{r}

simulate_data <- function(n = 10000, n_groups = 100, covariance_level=0) {
  # Simulate fixed effects
  
  sigma <- matrix(c(1, covariance_level, covariance_level, 
                    covariance_level, 1, covariance_level, 
                    covariance_level, covariance_level, 1), 3, 3)
  
  X <- MASS::mvrnorm(n = n, mu = c(0, 0, 0), Sigma = sigma)
  X1 <- X[, 1]
  X2 <- X[, 2]
  X3 <- X[, 3]

  # Simulate random effects groups
  Z1 <- sample(1:n_groups, n, replace = TRUE)
  random_effect_contributions_z1 <- rnorm(n_groups, mean = 0, sd = 1)[Z1]

  # Coefficients for fixed effects
  beta1 <- 1
  beta2 <- sqrt(2)
  beta3 <- sqrt(3)

  # Linear predictor
  eta <- beta1*X1 + beta2*X2 + beta3*X3 + random_effect_contributions_z1

  # Binomial with logit link
  p_logit <- exp(eta) / (1 + exp(eta))
  y_logit_bin <- rbinom(n, size = 1, prob = p_logit)
  data_logit <- data.frame(y_logit_bin, X1, X2, X3, Z1)

  # Binomial with probit link
  p_probit <- pnorm(eta)
  y_probit_bin <- rbinom(n, size = 1, prob = p_probit)
  data_probit <- data.frame(y_probit_bin, X1, X2, X3, Z1)

  # Poisson with log link
  lambda <- exp(eta)
  y_pois <- rpois(n, lambda = lambda)
  data_poisson <- data.frame(y_pois, X1, X2, X3, Z1)

  list(binomial_logit = data_logit, binomial_probit = data_probit, poisson = data_poisson)
}

```


```{r}
# Example usage:
set.seed(69) 
datasets <- simulate_data()

head(datasets$binomial_logit)
head(datasets$binomial_probit)
head(datasets$poisson)

glmm_logit <- y_logit_bin ~ X1 + X2 + X3 + f(Z1, model="iid")
glmm_probit <- y_probit_bin ~ X1 + X2 + X3 + f(Z1, model="iid")
glmm_log <- y_pois ~ X1 + X2 + X3 + f(Z1, model="iid")


model_logit <- VariableImportanceINLA::perform_inla_analysis(datasets$binomial_logit, glmm_logit, family = "binomial", link_func = "logit")
model_probit <- VariableImportanceINLA::perform_inla_analysis(datasets$binomial_probit, glmm_probit, family = "binomial", link_func = "probit")
model_log <- VariableImportanceINLA::perform_inla_analysis(datasets$poisson, glmm_log, family = "poisson", link_func = "log")

dist_logit <- pi^2/3
dist_probit <- 1


SVD_logit <- VariableImportanceINLA::SVD_decomp(datasets$binomial_logit[, c("X1", "X2", "X3")])
SVD_probit <- VariableImportanceINLA::SVD_decomp(datasets$binomial_probit[, c("X1", "X2", "X3")])
SVD_poisson <- VariableImportanceINLA::SVD_decomp(datasets$poisson[, c("X1", "X2", "X3")])


samp_logit <- inla.posterior.sample(model_logit, n=1)
samp_probit <- inla.posterior.sample(model_probit, n=1)
samp_poisson <- inla.posterior.sample(model_log, n=1)

output_length=length(samp_poisson[[1]]$latent)

pattern_random <- paste0("^", "Z1", ":")
latent <- rownames(samp_logit[[1]]$latent)
random <- grep(pattern_random, latent, value = TRUE)

random_logit <- c()
random_probit <- c()
random_poisson <- c()

random_samples_logit <- samp_logit[[1]]$latent[random, , drop = FALSE]
random_samples_probit <- samp_probit[[1]]$latent[random, , drop = FALSE]
random_samples_poisson <- samp_poisson[[1]]$latent[random, , drop = FALSE]

random_logit <- c(random_logit, var(random_samples_logit))
random_probit <- c(random_probit, var(random_samples_probit))
random_poisson <- c(random_poisson, var(random_samples_poisson))

random_logit
random_probit
random_poisson


fixed_samples_logit <- c()
fixed_samples_probit <- c()
fixed_samples_poisson <- c()

imp_samples_logit <- c()
imp_samples_probit <- c()
imp_samples_poisson <- c()

for (i in 1:3) {
  fixed <- grep(paste0("^", "X", i, ":"), latent, value = TRUE)
  fixed_samples_logit <- c(fixed_samples_logit, samp_logit[[1]]$latent[fixed, , drop = FALSE])
  fixed_samples_probit <- c(fixed_samples_probit, samp_probit[[1]]$latent[fixed, , drop = FALSE])
  fixed_samples_poisson <- c(fixed_samples_poisson, samp_poisson[[1]]$latent[fixed, , drop = FALSE])
}

samp_logit[[1]]$latent[fixed, , drop = FALSE]

fixed_samples_logit
imp_samples_logit <- c(imp_samples_logit, SVD_logit$lambda^2 %*% fixed_samples_logit^2)
imp_samples_probit <- c(imp_samples_probit, SVD_probit$lambda^2 %*% fixed_samples_probit^2)
imp_samples_poisson <- c(imp_samples_poisson, SVD_poisson$lambda^2 %*% fixed_samples_poisson^2)


imp_samples_logit


intercept <- samp_poisson[[1]]$latent[output_length-length(fixed_samples_poisson)]

intercept <- summary(model_log)$fixed[1]
lambda_pois <- exp(intercept + 0.5)
dist_log <- log(1 + 1/lambda_pois)

dist_log

imp_random_logit <- random_logit/(dist_logit + random_logit + sum(imp_samples_logit))
imp_random_probit <- random_probit/(dist_probit + random_probit + sum(imp_samples_probit))
imp_random_poisson <- random_poisson/(dist_log + random_poisson + sum(imp_samples_poisson))

imp_fixed_logit <- imp_samples_logit/(dist_logit + random_logit + sum(imp_samples_logit))
imp_fixed_probit <- imp_samples_probit/(dist_probit + random_probit + sum(imp_samples_probit))
imp_fixed_poisson <- imp_samples_poisson/(dist_log + random_poisson + sum(imp_samples_poisson))

expected_logit <- (1)/(dist_logit + 1 + 2 + 3 + 1)
expected_probit <- (1)/(dist_probit + 1 + 2 + 3 + 1)
expected_poisson <- (1)/(dist_log + 1 + 2 + 3 + 1)

imp_random_logit
imp_random_probit
imp_random_poisson

imp_fixed_logit
imp_fixed_probit
imp_fixed_poisson

expected_logit
expected_probit
expected_poisson

R2m_logit <- sum(imp_samples_logit)/(sum(imp_samples_logit) + sum(random_logit) + dist_logit) 
R2m_probit <- sum(imp_samples_probit)/(sum(imp_samples_probit) + sum(random_probit) + dist_probit)
R2m_pois <- sum(imp_samples_poisson)/(sum(imp_samples_poisson) + sum(random_poisson) + dist_log)

R2c_logit <- (sum(imp_samples_logit) + sum(random_logit))/(sum(imp_samples_logit) + sum(random_logit) + dist_logit)
R2c_probit <- (sum(imp_samples_probit) + sum(random_probit))/(sum(imp_samples_probit) + sum(random_probit) + dist_probit)
R2c_poisson <- (sum(imp_samples_poisson) + sum(random_poisson))/(sum(imp_samples_poisson) + sum(random_poisson) + dist_log)


R2m_logit
R2m_probit
R2m_pois


R2c_logit
R2c_probit
R2c_poisson

```


```{r}
extract_importance <- function(model, data, dist_factor) {
  # Decompose fixed effects matrix using SVD
  SVD <- VariableImportanceINLA::SVD_decomp(data[, c("X1", "X2", "X3")])
  
  # Sample from the posterior distribution
  sample_post <- inla.posterior.sample(model, n = 1)
  
  # Extract latent effects names
  latent_names <- rownames(sample_post[[1]]$latent)
  
  # Identify random effects using the pattern
  pattern_random <- paste0("^", "Z1", ":")
  random_indices <- grep(pattern_random, latent_names, value = TRUE)
  random_samples <- sample_post[[1]]$latent[random_indices, , drop = FALSE]
  
  # Variance of random effects
  var_random <- var(random_samples)
  
  # Process fixed effects
  fixed_effects <- numeric(3)
  fixed_imp <- numeric(3)
  for (i in 1:3) {
    fixed_indices <- grep(paste0("^", "X", i, ":"), latent_names, value = TRUE)
    fixed_samples <- sample_post[[1]]$latent[fixed_indices, , drop = FALSE]

    fixed_effects[i] <- fixed_samples
  }

  
  fixed_imp <- (SVD$lambda^2 %*% (fixed_effects^2))

  
  # Calculate overall importances
  total_var = as.double(dist_factor + var_random + sum(fixed_imp))
  
  imp_random <- var_random / total_var
  imp_fixed <- fixed_imp / total_var
  
  r2m <- sum(fixed_imp) / total_var
  r2c <- (sum(fixed_imp) + var_random) / total_var
  
  # Returning as a list
  list(
    random_importance = imp_random,
    fixed_importance = imp_fixed,
    r2m = r2m,
    r2c = r2c,
    expected_importance = (1) / (dist_factor + 1 + 2 + 3 + 1),
    expected_r2m = (1 + 2 + 3) / (dist_factor + 1 + 2 + 3 + 1),
    expected_r2c = (1 + 2 + 3 + 1) / (dist_factor + 1 + 2 + 3 + 1)
  )
}


# Example of how you might integrate this into your simulation function
run_simulation <- function(n_sim = 5, covariance_level = 0, include_probit = FALSE) {
  importances <- vector("list", n_sim)
  
  pb <- txtProgressBar(min = 0, max = n_sim, initial = 0, style = 3)
  
  for (i in 1:n_sim) {
    datasets <- simulate_data(covariance_level = covariance_level)

    
    glmm_logit <- y_logit_bin ~ X1 + X2 + X3 + f(Z1, model="iid")
    glmm_pois <- y_pois ~ X1 + X2 + X3 + f(Z1, model="iid")
    
    model_logit <- VariableImportanceINLA::perform_inla_analysis(datasets$binomial_logit, glmm_logit, family = "binomial", link_func = "logit")
    model_pois <- VariableImportanceINLA::perform_inla_analysis(datasets$poisson, glmm_pois, family = "poisson", link_func = "log")
    
    importances[[i]] <- list(
      logit = extract_importance(model_logit, datasets$binomial_logit, pi^2 / 3),
      poisson = extract_importance(model_pois, datasets$poisson, log(1 + 1/exp(summary(model_pois)$fixed[1] + 0.5)))
    )
    
    if (include_probit) {
      glmm_probit <- y_probit_bin ~ X1 + X2 + X3 + f(Z1, model="iid")
      model_probit <- VariableImportanceINLA::perform_inla_analysis(datasets$binomial_probit, glmm_probit, family = "binomial", link_func = "probit")
      importances[[i]]$probit = extract_importance(model_probit, datasets$binomial_probit, 1)
    }
    setTxtProgressBar(pb, i)
  }
  close(pb)
  return(importances)
}

```

```{r}
sim_test <- run_simulation(n_sim=500)
```

```{r}
# Run simulation for all covariance levels:

total_simulation <- function(n = 10000, n_groups = 100, covariance = c(0, 0.1, 0.5, 0.9), n_sim = 500){
  pb <- txtProgressBar(min = 0, max = n_sim, initial = 0, style = 3)
  sims <- vector("list", length(covariance))
  
  for (i in 1:covariance){
    sims[[i]] <- run_simulation(n_sim = n_sim, covariance_level = covariance[i], include_probit = FALSE)
    setTxtProgressBar(pb, i)
  }
  close(pb)
  return(sims)
}

test <- total_simulation(n = 10000, n_groups = 100, covariance = c(0, 0.1), n_sim = 2)


sim_test <- run_simulation(n_sim=5, covariance_level=0.4, include_probit=FALSE)

#0.4 in correlation seems to work, but I cant go higher if I want INLA to work

```

```{r}
```


```{r}
# Saving the entire sim_test object as an RDS file
saveRDS(sim_test, "simulation_19.04.rds")

# To load this file back into R:
loaded_sim_test <- readRDS("simulation_19.04.rds")


# Install and load necessary package
if (!require("jsonlite")) install.packages("jsonlite")
library(jsonlite)

# Convert the sim_test object to JSON and save to a file
write_json(sim_test, "simulation_19.04.json")

```


```{r}
datasets <- simulate_data()
library(rptR)
rptR_logit <- rptBinary(y_logit_bin ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets$binomial_logit, nboot = 10, npermut = 0, link="logit", adjusted = FALSE)
rptR_probit <- rptBinary(y_probit_bin ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets$binomial_probit, nboot = 10, npermut = 0, link="probit", adjusted = FALSE)
rptR_pois <- rptPoisson(y_pois ~ X1 + X2 + X3 + (1 | Z1), grname =  
    c("Fixed", "Z1"), data = datasets$poisson, link="log", nboot = 10, npermut = 0, adjusted=FALSE)
```

```{r}
Stoffel_logit <- rptR_logit$R$Z1[2]
Stoffel_probit <- rptR_probit$R$Z1[2]
Stoffel_pois <- rptR_pois$R$Z1[2]

Stoffel_logit_R2m <- rptR_logit$R$Fixed[2]
Stoffel_probit_R2m <- rptR_probit$R$Fixed[2]
Stoffel_pois_R2m <- rptR_pois$R$Fixed[2]

Stoffel_logit_R2c <- rptR_logit$R$Fixed[2] + rptR_logit$R$Z1[2]
Stoffel_probit_R2c <- rptR_probit$R$Fixed[2] + rptR_probit$R$Z1[2]
Stoffel_pois_R2c <- rptR_pois$R$Fixed[2] + rptR_pois$R$Z1[2]

Stoffel_logit
Stoffel_probit
Stoffel_pois

Stoffel_logit_R2m
Stoffel_logit_R2c

Stoffel_probit_R2m
Stoffel_probit_R2c

Stoffel_pois_R2m
Stoffel_pois_R2c

```

```{r}
# Function to extract averages for a given model, with detailed fixed effects handling
extract_averages <- function(sim_data, model) {
  # Aggregate fixed effect importances into a matrix and calculate column means
  fixed_importances <- do.call(rbind, lapply(sim_data, function(x) t(x[[model]]$fixed_importance)))
  average_fixed_importance <- colMeans(fixed_importances)

  # Other calculations for the model
  average_random_importance <- mean(sapply(sim_data, function(x) x[[model]]$random_importance))
  average_r2m <- mean(sapply(sim_data, function(x) x[[model]]$r2m))
  average_r2c <- mean(sapply(sim_data, function(x) x[[model]]$r2c))
  average_expected_importance <- mean(sapply(sim_data, function(x) x[[model]]$expected_importance))

  list(
    average_random_importance = average_random_importance,
    average_fixed_importance = average_fixed_importance,
    average_r2m = average_r2m,
    average_r2c = average_r2c,
    average_expected_importance = average_expected_importance
  )
}

# Extract averages for Logit and Poisson models
averages_logit <- extract_averages(sim_test, "logit")
averages_poisson <- extract_averages(sim_test, "poisson")

# Print results
print("Averages for Logit Model:")
print(averages_logit)
print("Averages for Poisson Model:")
print(averages_poisson)

averages_logit$average_expected_importance*3

```

```{r}
# Function to extract averages and 95% quantiles for a given model
extract_averages_and_quantiles <- function(sim_data, model) {
  # Collect all fixed effect importances
  fixed_importances_list <- lapply(sim_data, function(x) t(x[[model]]$fixed_importance))
  fixed_importances <- do.call(rbind, fixed_importances_list)
  
  # Calculate average and 95% quantile for fixed effects
  average_fixed_importance <- colMeans(fixed_importances)
  quantile_fixed_importance <- apply(fixed_importances, 2, quantile, probs = c(0.025, 0.975))

  # Collect random importance, R2m, R2c, and expected importance
  random_importances <- sapply(sim_data, function(x) x[[model]]$random_importance)
  r2m_values <- sapply(sim_data, function(x) x[[model]]$r2m)
  r2c_values <- sapply(sim_data, function(x) x[[model]]$r2c)
  expected_importances <- sapply(sim_data, function(x) x[[model]]$expected_importance)
  expected_r2m <- sapply(sim_data, function(x) x[[model]]$expected_r2m)
  expected_r2c <- sapply(sim_data, function(x) x[[model]]$expected_r2c)

  # Calculate mean and 95% quantile for each metric
  average_random_importance <- mean(random_importances)
  quantile_random_importance <- quantile(random_importances, probs = c(0.025, 0.975))

  average_r2m <- mean(r2m_values)
  quantile_r2m <- quantile(r2m_values, probs = c(0.025, 0.975))

  average_r2c <- mean(r2c_values)
  quantile_r2c <- quantile(r2c_values, probs = c(0.025, 0.975))

  average_expected_importance <- mean(expected_importances)
  quantile_expected_importance <- quantile(expected_importances, probs = c(0.025, 0.975))
  
  average_expected_r2m <- mean(expected_r2m)
  quantile_expected_r2m <- quantile(expected_r2m, probs = c(0.025, 0.975))
  
  average_expected_r2c <- mean(expected_r2c)
  quantile_expected_r2c <- quantile(expected_r2c, probs = c(0.025, 0.975))

  list(
    average_random_importance = average_random_importance,
    quantile_random_importance = quantile_random_importance,
    average_fixed_importance = average_fixed_importance,
    quantile_fixed_importance = quantile_fixed_importance,
    average_r2m = average_r2m,
    quantile_r2m = quantile_r2m,
    average_r2c = average_r2c,
    quantile_r2c = quantile_r2c,
    average_expected_importance = average_expected_importance,
    quantile_expected_importance = quantile_expected_importance,
    average_expected_r2m = average_expected_r2m,
    quantile_expected_r2m = quantile_expected_r2m,
    average_expected_r2c = average_expected_r2c,
    quantile_expected_r2c = quantile_expected_r2c
  )
}

# Example usage
averages_logit <- extract_averages_and_quantiles(sim_test, "logit")
averages_poisson <- extract_averages_and_quantiles(sim_test, "poisson")

# Print results for Logit model
print("Logit Model - Averages and Quantiles:")
print(averages_logit)


print("Poisson Model - Averages and Quantiles:")
print(averages_poisson)
```


```{r}
library(ggplot2)

# Prepare data for plotting
random_importances_logit <- data.frame(
  Model = rep(c("Logit"), each = length(sim_test)),
  RandomImportance = c(sapply(sim_test, function(x) x$logit$random_importance)
                       #sapply(sim_test, function(x) x$poisson$random_importance)
                       ),
  ExpectedImportance = c(rep(sim_test[[1]]$logit$expected_importance, length(sim_test))
                         #rep(sim_test[[1]]$poisson$expected_importance, length(sim_test))
                         )
)

#StoffelValues <- c(Stoffel_logit)

# Plotting
random_logit_plot <- ggplot(random_importances_logit, aes(x = RandomImportance)) +
  geom_histogram(bins = 30, fill = "#C6CDF7", alpha = 0.7, color = "black") +
  facet_wrap(~ Model, scales = "free") +
  geom_vline(aes(xintercept = ExpectedImportance), color = "green", linetype = "dashed", linewidth = 1) +
  geom_vline(data = data.frame(Model = c("Logit"), StoffelValue = Stoffel_logit),
             aes(xintercept = StoffelValue), color = "magenta", linetype = "dashed", linewidth = 1) +
  labs(title = "Random Importances with Expected Importance",
       x = "Random Importance", y = "Frequency") +
  theme_minimal() +
  theme(legend.position = "none",
      axis.title.x = element_text(size = 24),
      axis.title.y = element_text(size = 24),
      axis.text.x = element_text(size = 24),
      axis.text.y = element_text(size = 24)
      )

random_logit_plot


random_importances_pois <- data.frame(
  Model = rep(c("Poisson"), each = length(sim_test)),
  RandomImportance = c(#sapply(sim_test, function(x) x$logit$random_importance),
                       sapply(sim_test, function(x) x$poisson$random_importance)),
  ExpectedImportance = c(#rep(sim_test[[1]]$logit$expected_importance, length(sim_test)),
                         rep(sim_test[[1]]$poisson$expected_importance, length(sim_test)))
)

#StoffelValues <- c(Stoffel_pois)

# Plotting
random_poisson_plot <- ggplot(random_importances_pois, aes(x = RandomImportance)) +
  geom_histogram(bins = 30, fill = "#C6CDF7", alpha = 0.7, color = "black") +
  facet_wrap(~ Model, scales = "free") +
  geom_vline(aes(xintercept = ExpectedImportance), color = "green", linetype = "dashed", linewidth = 1) +
  geom_vline(data = data.frame(Model = c("Poisson"), StoffelValue = Stoffel_pois),
             aes(xintercept = StoffelValue), color = "magenta", linetype = "dashed", linewidth = 1) +
  labs(title = "Random Importances with Expected Importance",
       x = "Random Importance", y = "Frequency") +
  theme_minimal() +
  theme(legend.position = "none",
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 24),
    axis.text.y = element_text(size = 24)
  )

random_poisson_plot
```



```{r}
library(ggplot2)

# Function to prepare data and plot for a given model
plot_fixed_importances <- function(data, model_name, title_prefix) {
  # Create a list to collect data frames for each fixed effect
  fixed_effects_data <- list()
  
  # Iterate over each fixed effect
  for (i in 1:3) {
    fixed_importances <- data.frame(
      Simulation = rep(1:length(data), each = 1),
      FixedEffect = paste0("X", i),
      Importance = sapply(data, function(x) x[[model_name]]$fixed_importance[i]),
      ExpectedImportance = (i * data[[1]][[model_name]]$expected_importance)
    )
    fixed_effects_data[[i]] <- fixed_importances
  }
  
  # Combine all fixed effects data into one data frame
  all_fixed_importances <- do.call(rbind, fixed_effects_data)
  # This requires transforming the Importance values to a less precise format before plotting
all_fixed_importances$Importance <- round(all_fixed_importances$Importance, 4)  # Round to fewer decimal places

  
  # Plotting
  ggplot(all_fixed_importances, aes(x = Importance)) +
    geom_histogram(bins = 30, fill = "#E6A0C4", alpha = 0.7, color = "black") +
    facet_wrap(~ FixedEffect, scales = "free") +
    geom_vline(aes(xintercept = ExpectedImportance), color = "green", linetype = "dashed", size = 1) +
    labs(title = paste(title_prefix, "Fixed Effect Importances with Expected Importances"),
         x = "Fixed Effect Importance", y = "Frequency") +
    theme_minimal() +
    theme(legend.position = "none",
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 24),
    axis.text.y = element_text(size = 24)
    ) 
}


# Plot for Logit model
fixed_logit_plot <- plot_fixed_importances(sim_test, "logit", "Logit Model:")

# Plot for Poisson model
fixed_poisson_plot <- plot_fixed_importances(sim_test, "poisson", "Poisson Model:")

fixed_logit_plot

fixed_poisson_plot
#E6A0C4
#F1BB7B
```

```{r}
logit_r2_data <- data.frame(
  Type = rep(c("Marginal", "Conditional"), each = length(sim_test)),
  Value = c(sapply(sim_test, function(x) x$logit$r2m),
            sapply(sim_test, function(x) x$logit$r2c))
)

poisson_r2_data <- data.frame(
  Type = rep(c("Marginal", "Conditional"), each = length(sim_test)),
  Value = c(sapply(sim_test, function(x) x$poisson$r2m),
            sapply(sim_test, function(x) x$poisson$r2c))
)



logit_stoffel_r2_data <- data.frame(
  Type = c("Marginal", "Conditional"),
  Value = c(Stoffel_logit_R2m, Stoffel_logit_R2c)
)

poisson_stoffel_r2_data <- data.frame(
  Type = c("Marginal", "Conditional"),
  Value = c(Stoffel_pois_R2m, Stoffel_pois_R2c)
)

# Create data frames for expected R-squared values
expected_values_logit <- data.frame(
  Type = c("Marginal", "Conditional"),
  Value = c(averages_logit$average_expected_r2m, averages_logit$average_expected_r2c)
)

expected_values_poisson <- data.frame(
  Type = c("Marginal", "Conditional"),
  Value = c(averages_poisson$average_expected_r2m, averages_poisson$average_expected_r2c)
)

logit_stoffel_r2_data$Measure <- "Stoffel"
expected_values_logit$Measure <- "Expected"

poisson_stoffel_r2_data$Measure <- "Stoffel"
expected_values_poisson$Measure <- "Expected"

# Plotting for Logit model
r2_logit_plot <- ggplot(logit_r2_data, aes(x = Value)) +
  geom_histogram(bins = 30, fill = "#F1BB7B", color = "black", alpha = 0.7) +
  facet_wrap(~ Type, scales = "free") +
  geom_vline(data = logit_stoffel_r2_data, aes(xintercept = Value, color = Measure), linetype = "dashed", size = 1) + # , show.legend = FALSE
  geom_vline(data = expected_values_logit, aes(xintercept = Value, color = Measure), linetype = "dashed", size = 1) + # , show.legend = FALSE
  scale_color_manual(name = "Measure", values = c(Stoffel = "magenta", Expected = "green")) +
  labs(title = "Histogram of R-squared Values for Logit Model",
       x = "R-squared Value",
       y = "Count") +
  theme_minimal() +
  theme(legend.position = "none",
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 24),
    axis.text.y = element_text(size = 24)
    ) 

# Plotting for Poisson model
r2_poisson_plot <- ggplot(poisson_r2_data, aes(x = Value, fill = Type)) +
  geom_histogram(bins = 30, fill = "#F1BB7B", color = "black", alpha = 0.7) +
  facet_wrap(~ Type, scales = "free") +
  geom_vline(data = poisson_stoffel_r2_data, aes(xintercept = Value, color = Measure), linetype = "dashed", size = 1) + # , show.legend = FALSE
  geom_vline(data = expected_values_poisson, aes(xintercept = Value, color = Measure), linetype = "dashed", size = 1) + # , show.legend = FALSE
  scale_color_manual(name = "Measure", values = c(Stoffel = "magenta", Expected = "green")) +
  #scale_fill_manual(values = c("Marginal" = "#85D4E3", "Conditional" = "#F4B5BD")) +
  labs(title = "Histogram of R-squared Values for Poisson Model",
       x = "R-squared Value",
       y = "Count") +
  theme_minimal() +
  theme(legend.position = "none",
    axis.title.x = element_text(size = 24),
    axis.title.y = element_text(size = 24),
    axis.text.x = element_text(size = 24),
    axis.text.y = element_text(size = 24)
    ) 


# Output the plots
print(r2_logit_plot)
print(r2_poisson_plot)


```



```{r}
plot_folder <- "/Users/augustarnstad/Library/CloudStorage/OneDrive-NTNU/Semester_10/Master/Latex/Figures/Simulation study"

# Check if the folder exists, if not, create it
if (!dir.exists(plot_folder)) {
  dir.create(plot_folder)
}

ggsave(filename="Random_logit.png", plot=random_logit_plot, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="Random_poisson.png", plot=random_poisson_plot, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="Fixed_logit.png", plot=fixed_logit_plot, path=plot_folder, width = 16, height = 8, dpi = 300)
ggsave(filename="Fixed_poisson.png", plot=fixed_poisson_plot, path=plot_folder, width = 16, height = 8, dpi = 300)
ggsave(filename="R2_logit.png", plot=r2_logit_plot, path=plot_folder, width = 10, height = 6, dpi = 300)
ggsave(filename="R2_poisson.png", plot=r2_poisson_plot, path=plot_folder, width = 10, height = 6, dpi = 300)


# ggsave(filename="Binomial_probit_fixed.png", plot=fixed_effects_probit, path=plot_folder)
# ggsave(filename="Binomial_probit_random.png", plot=random_effects_probit, path=plot_folder)
# ggsave(filename="Binomial_probit_R2.png", plot=R2_plot_probit, path=plot_folder)
```

